namespace Terradue.GeoJson.Gml
{
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (DefinitionProxyType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeOrdinalEraType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeCalendarEraType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeReferenceSystemType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeOrdinalReferenceSystemType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeClockType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeCalendarType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeCoordinateSystemType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (IdentifiedObjectType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractGeneralOperationParameterType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (OperationParameterGroupType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (OperationParameterType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (OperationMethodType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractCoordinateOperationType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (PassThroughOperationType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (ConcatenatedOperationType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractGeneralTransformationType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TransformationType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractGeneralConversionType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (ConversionType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (EllipsoidType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (PrimeMeridianType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractDatumType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TemporalDatumBaseType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TemporalDatumType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (VerticalDatumType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (ImageDatumType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (EngineeringDatumType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (GeodeticDatumType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (CoordinateSystemAxisType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractCoordinateSystemType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (ObliqueCartesianCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TemporalCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AffineCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (CylindricalCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (PolarCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (SphericalCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (UserDefinedCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (LinearCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TimeCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (VerticalCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (CartesianCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (EllipsoidalCSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (AbstractGeneralDerivedCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (DerivedCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (ProjectedCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (GeocentricCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (GeographicCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (TemporalCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (ImageCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (EngineeringCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (VerticalCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (GeodeticCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (CompoundCRSType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (UnitDefinitionType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (ConventionalUnitType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (DerivedUnitType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (BaseUnitType))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof (DictionaryType))]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/gml/3.2")]
  [System.Xml.Serialization.XmlRootAttribute("Definition", Namespace = "http://www.opengis.net/gml/3.2",
    IsNullable = false)]
  public partial class DefinitionType : DefinitionBaseType
  {

    private string remarksField;

    [System.Xml.Serialization.XmlElementAttribute()]
    public string remarks
    {
      get { return remarksField; }
      set { remarksField = value; }
    }
  }
}