// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.GeoJson.Gml</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Terradue.GeoJson.Gml
{
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/gml/3.2")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/gml/3.2", IsNullable = false)]
  public partial class SecondDefiningParameter
  {

    private object itemField;

    [System.Xml.Serialization.XmlElementAttribute("inverseFlattening", typeof (MeasureType))]
    [System.Xml.Serialization.XmlElementAttribute("isSphere", typeof (bool))]
    [System.Xml.Serialization.XmlElementAttribute("semiMinorAxis", typeof (LengthType))]
    public object Item
    {
      get { return itemField; }
      set { itemField = value; }
    }
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
  public partial class arcType
  {

    private titleEltType[] titleField;

    private typeType typeField;

    private string arcroleField;

    private string title1Field;

    private showType showField;

    private bool showFieldSpecified;

    private actuateType actuateField;

    private bool actuateFieldSpecified;

    private string fromField;

    private string toField;

    public arcType()
    {
      typeField = typeType.arc;
    }

    [System.Xml.Serialization.XmlElementAttribute("title")]
    public titleEltType[] title
    {
      get { return titleField; }
      set { titleField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public typeType type
    {
      get { return typeField; }
      set { typeField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
      DataType = "anyURI")]
    public string arcrole
    {
      get { return arcroleField; }
      set { arcroleField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute("title", Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string title1
    {
      get { return title1Field; }
      set { title1Field = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public showType show
    {
      get { return showField; }
      set { showField = value; }
    }

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showSpecified
    {
      get { return showFieldSpecified; }
      set { showFieldSpecified = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public actuateType actuate
    {
      get { return actuateField; }
      set { actuateField = value; }
    }

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool actuateSpecified
    {
      get { return actuateFieldSpecified; }
      set { actuateFieldSpecified = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
      DataType = "NCName")]
    public string from
    {
      get { return fromField; }
      set { fromField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
      DataType = "NCName")]
    public string to
    {
      get { return toField; }
      set { toField = value; }
    }
  }
}
