// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.GeoJson.Gml</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Terradue.GeoJson.Gml
{
  [GeneratedCode("System.Xml", "4.0.30319.1")]
  [Serializable]
  [DesignerCategory("code")]
  [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/gml/3.2")]
  [XmlRoot(Namespace = "http://www.opengis.net/gml/3.2", IsNullable = false)]
  public class SecondDefiningParameter
  {
    private object itemField;

    [XmlElement("inverseFlattening", typeof (MeasureType))]
    [XmlElement("isSphere", typeof (bool))]
    [XmlElement("semiMinorAxis", typeof (LengthType))]
    public object Item
    {
      get { return itemField; }
      set { itemField = value; }
    }
  }

  [GeneratedCode("System.Xml", "4.0.30319.1")]
  [Serializable]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://www.w3.org/1999/xlink")]
  public class arcType
  {
    private actuateType actuateField;
    private bool actuateFieldSpecified;
    private string arcroleField;
    private string fromField;
    private showType showField;
    private bool showFieldSpecified;
    private string title1Field;
    private titleEltType[] titleField;
    private string toField;
    private typeType typeField;

    public arcType()
    {
      typeField = typeType.arc;
    }

    [XmlElement("title")]
    public titleEltType[] title
    {
      get { return titleField; }
      set { titleField = value; }
    }

    [XmlAttribute(Form = XmlSchemaForm.Qualified)]
    public typeType type
    {
      get { return typeField; }
      set { typeField = value; }
    }

    [XmlAttribute(Form = XmlSchemaForm.Qualified,
      DataType = "anyURI")]
    public string arcrole
    {
      get { return arcroleField; }
      set { arcroleField = value; }
    }

    [XmlAttribute("title", Form = XmlSchemaForm.Qualified)]
    public string title1
    {
      get { return title1Field; }
      set { title1Field = value; }
    }

    [XmlAttribute(Form = XmlSchemaForm.Qualified)]
    public showType show
    {
      get { return showField; }
      set { showField = value; }
    }

    [XmlIgnore]
    public bool showSpecified
    {
      get { return showFieldSpecified; }
      set { showFieldSpecified = value; }
    }

    [XmlAttribute(Form = XmlSchemaForm.Qualified)]
    public actuateType actuate
    {
      get { return actuateField; }
      set { actuateField = value; }
    }

    [XmlIgnore]
    public bool actuateSpecified
    {
      get { return actuateFieldSpecified; }
      set { actuateFieldSpecified = value; }
    }

    [XmlAttribute(Form = XmlSchemaForm.Qualified,
      DataType = "NCName")]
    public string from
    {
      get { return fromField; }
      set { fromField = value; }
    }

    [XmlAttribute(Form = XmlSchemaForm.Qualified,
      DataType = "NCName")]
    public string to
    {
      get { return toField; }
      set { toField = value; }
    }
  }
}