// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>safe</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.ServiceModel.Ogc.Gml311;


namespace Terradue.GeoJson.GeoRss {
  using System.Xml.Serialization;


  public interface IGeoRSS {
    }


    [XmlIncludeAttribute(typeof(GeoRssWhere))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("_featureProperty", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public abstract partial class abstractFeaturePropertyType {
    }



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("where", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssWhere : abstractFeaturePropertyType, IGeoRSS {

        private object[] itemField;

        [XmlElementAttribute("CircleByCenterPoint", typeof(CircleByCenterPointType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("Envelope", typeof(EnvelopeType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("LineString", typeof(LineStringType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("Point", typeof(PointType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("Polygon", typeof(PolygonType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("MultiSurface", typeof(MultiSurfaceType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("MultiCurve", typeof(MultiCurveType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("MultiPolygon", typeof(MultiPolygonType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("MultiPoint", typeof(MultiPointType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("MultiLineString", typeof(MultiLineStringType), Namespace = "http://www.opengis.net/gml")]
        public object[] Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }

		[XmlAttributeAttribute("type")]
		public string Type {
			get;
			set;
		}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("point", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssPoint : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("line", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssLine : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("polygon", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssPolygon : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("box", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssBox : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("featuretypetag", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssFeatureType : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("featurename", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssFeatureName : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("relationshiptag", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssRelationshipTag : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("elev", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssElevation : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [XmlRootAttribute("radius", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssRadius : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }
}
