// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>safe</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.ServiceModel.Ogc.Gml311;


namespace Terradue.GeoJson.GeoRss10 {
  using System.Xml.Serialization;


  public interface IGeoRSS {
    }


    [XmlIncludeAttribute(typeof(GeoRss10Where))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("_featureProperty", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public abstract partial class abstractFeaturePropertyType {
    }



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("where", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10Where : abstractFeaturePropertyType, IGeoRSS {

        private object itemField;

        [XmlElementAttribute("CircleByCenterPoint", typeof(CircleByCenterPointType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("Envelope", typeof(EnvelopeType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("LineString", typeof(LineStringType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("Point", typeof(PointType), Namespace = "http://www.opengis.net/gml")]
        [XmlElementAttribute("Polygon", typeof(PolygonType), Namespace = "http://www.opengis.net/gml")]
        public object Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("point", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10Point : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("line", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10Line : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("polygon", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10Polygon : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("box", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10Box : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("featuretypetag", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10FeatureType : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("featurename", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10FeatureName : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("relationshiptag", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10RelationshipTag : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("elev", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10Elevation : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.georss.org/georss/10")]
    [XmlRootAttribute("radius", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public partial class GeoRss10Radius : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }


}
