// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>safe</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Xml.Serialization;
using Terradue.ServiceModel.Ogc.Gml311;

namespace Terradue.GeoJson.GeoRss10 {
  public interface IGeoRSS {
    }


    [XmlInclude(typeof(GeoRss10Where))]
    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("_featureProperty", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public abstract class abstractFeaturePropertyType {
    }



    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("where", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10Where : abstractFeaturePropertyType, IGeoRSS {

        private object itemField;

        [XmlElement("CircleByCenterPoint", typeof(CircleByCenterPointType), Namespace = "http://www.opengis.net/gml")]
        [XmlElement("Envelope", typeof(EnvelopeType), Namespace = "http://www.opengis.net/gml")]
        [XmlElement("LineString", typeof(LineStringType), Namespace = "http://www.opengis.net/gml")]
        [XmlElement("Point", typeof(PointType), Namespace = "http://www.opengis.net/gml")]
        [XmlElement("Polygon", typeof(PolygonType), Namespace = "http://www.opengis.net/gml")]
        public object Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("point", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10Point : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("line", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10Line : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("polygon", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10Polygon : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("box", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10Box : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("featuretypetag", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10FeatureType : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("featurename", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10FeatureName : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("relationshiptag", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10RelationshipTag : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("elev", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10Elevation : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }

    [GeneratedCode("System.Xml", "4.0.30319.1")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.georss.org/georss/10")]
    [XmlRoot("radius", Namespace = "http://www.georss.org/georss/10", IsNullable = false)]
    public class GeoRss10Radius : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
    }


}
