// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>safe</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.ServiceModel.Ogc.Gml311;
using System.Xml;
using System.Xml.Linq;
using Terradue.GeoJson.Geometry;


namespace Terradue.GeoJson.GeoRss {
    
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public static class GeoRssHelper {

        public static IGeoRSS Deserialize(XmlReader reader) {

            var node = XElement.Load(reader);
            reader = node.CreateReader();

            if (node.Name.NamespaceName != "http://www.georss.org/georss")
                throw new InvalidFormatException("The xml is not GeoRSS");

            if (node.Name.LocalName == "where") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssWhere));
                return (GeoRssWhere)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "point") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssPoint));
                return (GeoRssPoint)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "line") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssLine));
                return (GeoRssLine)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "polygon") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssPolygon));
                return (GeoRssPolygon)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "box") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssBox));
                return (GeoRssBox)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "featuretypetag") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssFeatureType));
                return (GeoRssFeatureType)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "featurename") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssFeatureName));
                return (GeoRssFeatureName)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "relationshiptag") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssRelationshipTag));
                return (GeoRssRelationshipTag)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "elev") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssElevation));
                return (GeoRssElevation)geoRssSerializer.Deserialize(reader);
            }

            if (node.Name.LocalName == "radius") {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssRadius));
                return (GeoRssRadius)geoRssSerializer.Deserialize(reader);
            }

            throw new NotImplementedException();

        }

        public static void Serialize(XmlWriter writer, IGeoRSS georss) {

            XmlSerializerNamespaces namespaces = new XmlSerializerNamespaces();
            namespaces.Add(string.Empty, string.Empty);
            namespaces.Add("georss", "http://www.georss.org/georss");


            if (georss is GeoRssWhere) {
                namespaces.Add("gml", "http://www.opengis.net/gml");
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssWhere));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssPoint) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssPoint));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssLine) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssLine));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssPolygon) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssPolygon));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssBox) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssBox));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssFeatureType) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssFeatureType));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssFeatureName) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssFeatureName));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssRelationshipTag) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssRelationshipTag));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssElevation) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssElevation));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }

            if (georss is GeoRssRadius) {
                XmlSerializer geoRssSerializer = new XmlSerializer(typeof(GeoRssRadius));
                geoRssSerializer.Serialize(writer,georss,namespaces);
            }
                
        }
            

    }

    public interface IGeoRSS {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeoRssWhere))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("_featureProperty", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public abstract partial class abstractFeaturePropertyType {
    }



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("where", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssWhere : abstractFeaturePropertyType, IGeoRSS {

        private object itemField;

        [System.Xml.Serialization.XmlElementAttribute("CircleByCenterPoint", typeof(CircleByCenterPointType), Namespace = "http://www.opengis.net/gml")]
        [System.Xml.Serialization.XmlElementAttribute("Envelope", typeof(EnvelopeType), Namespace = "http://www.opengis.net/gml")]
        [System.Xml.Serialization.XmlElementAttribute("LineString", typeof(LineStringType), Namespace = "http://www.opengis.net/gml")]
        [System.Xml.Serialization.XmlElementAttribute("Point", typeof(PointType), Namespace = "http://www.opengis.net/gml")]
        [System.Xml.Serialization.XmlElementAttribute("Polygon", typeof(PolygonType), Namespace = "http://www.opengis.net/gml")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("point", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssPoint : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("line", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssLine : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("polygon", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssPolygon : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("box", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssBox : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("featuretypetag", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssFeatureType : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("featurename", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssFeatureName : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("relationshiptag", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssRelationshipTag : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("elev", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssElevation : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.georss.org/georss")]
    [System.Xml.Serialization.XmlRootAttribute("radius", Namespace = "http://www.georss.org/georss", IsNullable = false)]
    public partial class GeoRssRadius : IGeoRSS {

        private string itemField;

        [XmlText]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
